<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFrameworks>roslyn4.8;roslyn5.0;roslyn5.9</TargetFrameworks>
	<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
	<IsRoslynComponent>true</IsRoslynComponent>
	<NoWarn>$(NoWarn);CA1716</NoWarn>
  </PropertyGroup>

  <ItemGroup>
	<Compile Include="../Common/*.cs" Link="Common/%(Filename).cs" />
  </ItemGroup>

  <ItemGroup>
	<None Remove="Templates/*.sbntxt" />
	<EmbeddedResource Include="Templates/*.sbntxt" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="AssemblyMetadata.Generators" PrivateAssets="All" />
	<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" PrivateAssets="all" />
	<PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" />
  </ItemGroup>

  <!-- Scriban (code in netstandard2.0; lib in net10+) -->
  <ItemGroup Condition=" '$(TargetFramework)' == 'roslyn4.8' ">
	<PackageReference Include="Scriban" PrivateAssets="all" IncludeAssets="Build" />
  </ItemGroup>

  <PropertyGroup Condition=" '$(TargetFramework)' == 'roslyn4.8' ">
	<PackageScribanIncludeSource>true</PackageScribanIncludeSource>
	<DefineConstants>$(DefineConstants);SCRIBAN_NO_ASYNC</DefineConstants>
  </PropertyGroup>

  <ItemGroup Condition=" '$(TargetFramework)' != 'roslyn4.8' ">
	<PackageReference Include="Scriban" PrivateAssets="all" GeneratePathProperty="true" />
  </ItemGroup>

  <PropertyGroup Condition=" '$(TargetFramework)' != 'roslyn4.8' ">
	<GetTargetPathDependsOn>$(GetTargetPathDependsOn);GetDependencyTargetPaths</GetTargetPathDependsOn>
  </PropertyGroup>

  <Target Name="GetDependencyTargetPaths" Condition=" '$(TargetFramework)' != 'roslyn4.8' ">
	<ItemGroup>
	  <TargetPathWithTargetPlatformMoniker Include="$(PkgScriban)/lib/netstandard2.0/Scriban.dll" IncludeRuntimeDependency="false" />
	</ItemGroup>
  </Target>

  <PropertyGroup Condition=" '$(TargetFramework)' == 'roslyn4.8' ">
	<TargetFrameworkIdentifier>.NETStandard</TargetFrameworkIdentifier>
	<TargetFrameworkVersion>v2.0</TargetFrameworkVersion>
	<TargetFrameworkMoniker>.NETStandard,Version=v2.0</TargetFrameworkMoniker>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(TargetFramework)' == 'roslyn5.0' ">
	<TargetFrameworkIdentifier>.NETCoreApp</TargetFrameworkIdentifier>
	<TargetFrameworkVersion>v10.0</TargetFrameworkVersion>
	<TargetFrameworkMoniker>.NETCoreApp,Version=v10.0</TargetFrameworkMoniker>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(TargetFramework)' == 'roslyn5.9' ">
	<TargetFrameworkIdentifier>.NETCoreApp</TargetFrameworkIdentifier>
	<TargetFrameworkVersion>v10.0</TargetFrameworkVersion>
	<TargetFrameworkMoniker>.NETCoreApp,Version=v10.0</TargetFrameworkMoniker>
  </PropertyGroup>

</Project>
