<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
	<TargetFrameworks>net10.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
	<ProjectReference Include="../../src/Immediate.Handlers.Shared/Immediate.Handlers.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="../../src/Immediate.Handlers.Analyzers/Immediate.Handlers.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false">
	  <SetTargetFramework>TargetFramework=roslyn5.0</SetTargetFramework>
	</ProjectReference>
	<ProjectReference Include="../../src/Immediate.Handlers.CodeFixes/Immediate.Handlers.CodeFixes.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false">
	  <SetTargetFramework>TargetFramework=roslyn5.0</SetTargetFramework>
	</ProjectReference>
	<ProjectReference Include="../../src/Immediate.Handlers.Generators/Immediate.Handlers.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false">
	  <SetTargetFramework>TargetFramework=roslyn5.0</SetTargetFramework>
	</ProjectReference>
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.AspNetCore.OpenApi" />
	<PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

</Project>
