//HintName: IH..FirstHandler.g.cs
// <auto-generated />
#nullable enable

#pragma warning disable CS1591

partial class FirstHandler
{
	public sealed partial class Handler : global::Immediate.Handlers.Shared.IHandler<global::FirstHandler.Query, int>
	{
		private readonly global::FirstHandler.HandleBehavior _handleBehavior;
		private readonly global::LoggingBehavior<global::FirstHandler.Query, int> _loggingBehavior;

		public Handler(
			global::FirstHandler.HandleBehavior handleBehavior,
			global::LoggingBehavior<global::FirstHandler.Query, int> loggingBehavior
		)
		{
			var handlerType = typeof(FirstHandler);

			_handleBehavior = handleBehavior;

			_loggingBehavior = loggingBehavior;
			_loggingBehavior.HandlerType = handlerType;

			_loggingBehavior.SetInnerHandler(_handleBehavior);
		}

		public async global::System.Threading.Tasks.ValueTask<int> HandleAsync(
			global::FirstHandler.Query request,
			global::System.Threading.CancellationToken cancellationToken = default
		)
		{
			return await _loggingBehavior
				.HandleAsync(request, cancellationToken)
				.ConfigureAwait(false);
		}
	}

	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	public sealed class HandleBehavior : global::Immediate.Handlers.Shared.Behavior<global::FirstHandler.Query, int>
	{

		public HandleBehavior(
		)
		{
		}

		public override async global::System.Threading.Tasks.ValueTask<int> HandleAsync(
			global::FirstHandler.Query request,
			global::System.Threading.CancellationToken cancellationToken
		)
		{
			return await global::FirstHandler
				.HandleAsync(
					request
					, cancellationToken
				)
				.ConfigureAwait(false);
		}
	}

	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddHandlers(
		global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
		global::Microsoft.Extensions.DependencyInjection.ServiceLifetime lifetime = global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Scoped
	)
	{
		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddTransient(services, typeof(global::LoggingBehavior<global::FirstHandler.Query, int>));
		
		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAdd(
			services,
			global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Describe(
				typeof(global::FirstHandler.Handler),
				typeof(global::FirstHandler.Handler),
				lifetime
			)
		);

		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAdd(
			services,
			global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Describe(
				typeof(global::Immediate.Handlers.Shared.IHandler<global::FirstHandler.Query, int>),
				typeof(global::FirstHandler.Handler),
				lifetime
			)
		);

		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAdd(
			services,
			global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Describe(
				typeof(global::FirstHandler.HandleBehavior),
				typeof(global::FirstHandler.HandleBehavior),
				lifetime
			)
		);

		return services;
	}
}
