//HintName: IH..SecondHandler.g.cs
// <auto-generated />
#nullable enable

#pragma warning disable CS1591

partial class SecondHandler
{
	public sealed partial class Handler : global::Immediate.Handlers.Shared.IHandler<global::SecondHandler.Command, global::System.ValueTuple>
	{
		private readonly global::SecondHandler.HandleBehavior _handleBehavior;
		private readonly global::LoggingBehavior<global::SecondHandler.Command, global::System.ValueTuple> _loggingBehavior;

		public Handler(
			global::SecondHandler.HandleBehavior handleBehavior,
			global::LoggingBehavior<global::SecondHandler.Command, global::System.ValueTuple> loggingBehavior
		)
		{
			var handlerType = typeof(SecondHandler);

			_handleBehavior = handleBehavior;

			_loggingBehavior = loggingBehavior;
			_loggingBehavior.HandlerType = handlerType;

			_loggingBehavior.SetInnerHandler(_handleBehavior);
		}

		public async global::System.Threading.Tasks.ValueTask<global::System.ValueTuple> HandleAsync(
			global::SecondHandler.Command request,
			global::System.Threading.CancellationToken cancellationToken = default
		)
		{
			return await _loggingBehavior
				.HandleAsync(request, cancellationToken)
				.ConfigureAwait(false);
		}
	}

	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	public sealed class HandleBehavior : global::Immediate.Handlers.Shared.Behavior<global::SecondHandler.Command, global::System.ValueTuple>
	{

		public HandleBehavior(
		)
		{
		}

		public override async global::System.Threading.Tasks.ValueTask<global::System.ValueTuple> HandleAsync(
			global::SecondHandler.Command request,
			global::System.Threading.CancellationToken cancellationToken
		)
		{
			await global::SecondHandler
				.HandleAsync(
					request
					, cancellationToken
				)
				.ConfigureAwait(false);

			return default;
		}
	}

	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddHandlers(
		global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
		global::Microsoft.Extensions.DependencyInjection.ServiceLifetime lifetime = global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Scoped
	)
	{
		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddTransient(services, typeof(global::LoggingBehavior<global::SecondHandler.Command, global::System.ValueTuple>));
		
		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAdd(
			services,
			global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Describe(
				typeof(global::SecondHandler.Handler),
				typeof(global::SecondHandler.Handler),
				lifetime
			)
		);

		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAdd(
			services,
			global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Describe(
				typeof(global::Immediate.Handlers.Shared.IHandler<global::SecondHandler.Command, global::System.ValueTuple>),
				typeof(global::SecondHandler.Handler),
				lifetime
			)
		);

		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAdd(
			services,
			global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Describe(
				typeof(global::SecondHandler.HandleBehavior),
				typeof(global::SecondHandler.HandleBehavior),
				lifetime
			)
		);

		return services;
	}
}
