//HintName: IH.ServiceCollectionExtensions.g.cs
// <auto-generated />
#nullable enable

#pragma warning disable CS1591

public static class HandlerServiceCollectionExtensions
{
	public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddTestsBehaviors(
		this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services
	)
	{
		
		return services;
	}

	public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddTestsHandlers(
		this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
		global::Microsoft.Extensions.DependencyInjection.ServiceLifetime lifetime = global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Scoped
	)
	{
		global::Dummy.GetUsersQuery.AddHandlers(services, lifetime);
		
		return services;
	}
}
